import React, { createContext, useContext, useState, ReactNode } from 'react';

interface LanguageContextType {
  language: 'ar' | 'en';
  toggleLanguage: () => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations = {
  en: {
    // Header
    'nav.home': 'Home',
    'nav.services': 'Services',
    'nav.projects': 'Projects',
    'nav.about': 'About',
    'nav.contact': 'Contact',
    'header.phone': '+966 50 XXX XXXX',
    'header.consultation': 'Free Consultation',
    
    // Hero
    'hero.title': 'Transform Your Home Into a',
    'hero.titleHighlight': 'Smart Haven',
    'hero.subtitle': 'Professional home automation installation services for lighting, security, audio, and climate control systems throughout Saudi Arabia',
    'hero.getQuote': 'Get Free Quote',
    'hero.viewWork': 'View Our Work',
    'hero.experience': 'Years Experience',
    'hero.homes': 'Homes Automated',
    'hero.certified': 'Certified Installers',
    'hero.warranty': '2-Year Warranty',
    'hero.warrantyDesc': 'On all installations',
    
    // Services
    'services.title': 'Our Smart Home Services',
    'services.subtitle': 'From basic automation to complete smart home transformation, we offer comprehensive installation services for all your home automation needs.',
    'services.lighting.title': 'Smart Lighting Control',
    'services.lighting.desc': 'Complete lighting automation with dimmer controls, mood lighting, RGB systems, and energy-efficient LED integration.',
    'services.lighting.feature1': 'On/Off automation',
    'services.lighting.feature2': 'Scene programming',
    'services.lighting.feature3': 'Energy saving',
    'services.lighting.feature4': 'Voice control',
    'services.sensors.title': 'Sensors & Automation',
    'services.sensors.desc': 'Advanced sensor systems for motion detection, temperature monitoring, security, and environmental control.',
    'services.sensors.feature1': 'Motion detection',
    'services.sensors.feature2': 'Temperature sensors',
    'services.sensors.feature3': 'Door/window sensors',
    'services.sensors.feature4': 'Leak detection',
    'services.audio.title': 'Audio & Sound Systems',
    'services.audio.desc': 'Whole-house audio distribution with multi-room streaming, voice control, and home theater installation.',
    'services.audio.feature1': 'Multi-room audio',
    'services.audio.feature2': 'Voice control',
    'services.audio.feature3': 'Home theater',
    'services.audio.feature4': 'Outdoor audio',
    'services.curtains.title': 'Shutters & Curtains',
    'services.curtains.desc': 'Motorized window treatments with smart controls, scheduling, and integration with lighting systems.',
    'services.curtains.feature1': 'Motorized blinds',
    'services.curtains.feature2': 'App control',
    'services.curtains.feature3': 'Scheduled operation',
    'services.curtains.feature4': 'Privacy automation',
    'services.garage.title': 'Garage Door Control',
    'services.garage.desc': 'Smart garage door systems with remote access, security integration, and smartphone notifications.',
    'services.garage.feature1': 'Remote access',
    'services.garage.feature2': 'Security integration',
    'services.garage.feature3': 'Multiple doors',
    'services.garage.feature4': 'Smart notifications',
    'services.climate.title': 'Climate Control (AC)',
    'services.climate.desc': 'Smart thermostat installation with zone control, energy optimization, and integration with other systems.',
    'services.climate.feature1': 'Smart thermostats',
    'services.climate.feature2': 'Zone control',
    'services.climate.feature3': 'Energy optimization',
    'services.climate.feature4': 'Remote management',
    'services.security.title': 'Safety & Security Systems',
    'services.security.desc': 'Comprehensive security with CCTV cameras, smart locks, alarm systems, and 24/7 monitoring capabilities.',
    'services.security.feature1': 'CCTV installation',
    'services.security.feature2': 'Smart locks',
    'services.security.feature3': 'Alarm systems',
    'services.security.feature4': '24/7 monitoring',
    'services.learnMore': 'Learn More',
    'services.getQuote': 'Get Custom Quote for All Services',
    
    // How It Works
    'howItWorks.title': 'How We Transform Your Home',
    'howItWorks.subtitle': 'Our proven 4-step process ensures a seamless smart home installation experience from consultation to ongoing support.',
    'howItWorks.step1.title': 'Free Consultation',
    'howItWorks.step1.desc': 'Our certified technicians visit your home to assess your needs and provide a customized solution tailored to your lifestyle.',
    'howItWorks.step2.title': 'Custom Design',
    'howItWorks.step2.desc': 'We create a detailed installation plan with 3D renderings and technical specifications for your home automation system.',
    'howItWorks.step3.title': 'Professional Installation',
    'howItWorks.step3.desc': 'Our experienced team installs and configures all systems with minimal disruption to your daily routine.',
    'howItWorks.step4.title': 'Training & Support',
    'howItWorks.step4.desc': 'We train you on system operation and provide ongoing support, maintenance, and 24/7 technical assistance.',
    'howItWorks.learnMore': 'Learn more about this step →',
    'howItWorks.startJourney': 'Start Your Smart Home Journey Today',
    
    // Gallery
    'gallery.title': 'Our Recent Projects',
    'gallery.subtitle': 'See how we\'ve transformed homes across Saudi Arabia with our smart automation solutions.',
    'gallery.viewAll': 'View All Projects',
    
    // Benefits
    'benefits.title': 'Why Choose Smart Home Automation?',
    'benefits.subtitle': 'Transform your lifestyle while saving money and increasing your home\'s value with our professional automation solutions.',
    'benefits.security.title': 'Enhanced Security',
    'benefits.security.desc': '24/7 monitoring and control with smart locks, cameras, and alarm systems for complete peace of mind.',
    'benefits.security.stat': '95% crime reduction',
    'benefits.savings.title': 'Energy Savings',
    'benefits.savings.desc': 'Reduce electricity bills by up to 30% with smart lighting, climate control, and automated systems.',
    'benefits.savings.stat': '30% bill reduction',
    'benefits.convenience.title': 'Ultimate Convenience',
    'benefits.convenience.desc': 'Control everything from your smartphone - lights, temperature, security, and entertainment systems.',
    'benefits.convenience.stat': 'One-touch control',
    'benefits.value.title': 'Increased Property Value',
    'benefits.value.desc': 'Smart homes sell for 10-15% more than traditional homes and attract more buyers.',
    'benefits.value.stat': '15% value increase',
    'benefits.time.title': 'Time Saving',
    'benefits.time.desc': 'Automated routines and schedules save hours each week on manual home management tasks.',
    'benefits.time.stat': '5+ hours saved weekly',
    'benefits.lifestyle.title': 'Improved Lifestyle',
    'benefits.lifestyle.desc': 'Better sleep, mood lighting, perfect temperature, and entertainment at your fingertips.',
    'benefits.lifestyle.stat': '100% satisfaction',
    'benefits.ready.title': 'Ready to Experience These Benefits?',
    'benefits.ready.desc': 'Join hundreds of satisfied customers who have transformed their homes with Offer Arabiya\'s smart automation solutions.',
    'benefits.schedule': 'Schedule Free Consultation',
    'benefits.calculate': 'Calculate Your Savings',
    
    // Cost Calculator
    'calculator.title': 'Smart Home Cost Calculator',
    'calculator.subtitle': 'Get an instant estimate for your smart home automation project. Customize based on your home size and desired features.',
    'calculator.homeSize': 'Home Size (Square Meters)',
    'calculator.rooms': 'Number of Rooms',
    'calculator.services': 'Desired Services (Select all that apply)',
    'calculator.budget': 'Budget Range (SAR)',
    'calculator.calculate': 'Calculate Estimate',
    'calculator.estimate': 'Your Estimate',
    'calculator.total': 'Total Investment',
    'calculator.monthly': 'Monthly Payment (24 months)',
    'calculator.savings': 'Annual Energy Savings',
    'calculator.included': 'What\'s Included:',
    'calculator.installation': 'Professional installation & setup',
    'calculator.warranty': '2-year warranty on all equipment',
    'calculator.app': 'Mobile app configuration',
    'calculator.support': 'Training & 24/7 support',
    'calculator.getQuote': 'Get Detailed Quote',
    'calculator.ready': 'Ready to Calculate?',
    'calculator.readyDesc': 'Select your desired services and click calculate to see your personalized estimate.',
    
    // Testimonials
    'testimonials.title': 'What Our Customers Say',
    'testimonials.subtitle': 'Join hundreds of satisfied customers who have transformed their homes with our professional smart automation solutions.',
    'testimonials.rating': 'Average Rating',
    'testimonials.customers': 'Happy Customers',
    'testimonials.satisfaction': 'Satisfaction Rate',
    'testimonials.support': 'Support Available',
    'testimonials.join': 'Join Our Happy Customers',
    
    // Why Choose Us
    'whyChoose.title': 'Why Choose Offer Arabiya?',
    'whyChoose.subtitle': 'With over 7 years of experience and 500+ successful installations, we\'re Saudi Arabia\'s trusted smart home automation experts.',
    'whyChoose.experience.title': '7+ Years Experience',
    'whyChoose.experience.desc': 'Extensive experience in home automation with hundreds of successful installations across Saudi Arabia.',
    'whyChoose.customers.title': '500+ Satisfied Customers',
    'whyChoose.customers.desc': 'Join our growing family of happy customers who trust us with their smart home needs.',
    'whyChoose.certified.title': 'Certified Technicians',
    'whyChoose.certified.desc': 'Our team consists of certified professionals with ongoing training in the latest smart home technologies.',
    'whyChoose.warranty.title': '2-Year Warranty',
    'whyChoose.warranty.desc': 'Comprehensive warranty coverage on all installations with free maintenance and support.',
    'whyChoose.support.title': '24/7 Support',
    'whyChoose.support.desc': 'Round-the-clock technical support and maintenance services to keep your smart home running perfectly.',
    'whyChoose.consultation.title': 'Free Consultation',
    'whyChoose.consultation.desc': 'Complimentary home assessment and system design consultation with no obligation.',
    'whyChoose.certifications': 'Our Certifications & Partnerships',
    'whyChoose.promise': 'Our Promise to You',
    'whyChoose.quality': 'Quality Guarantee',
    'whyChoose.onTime': 'On-Time',
    'whyChoose.delivery': 'Project Delivery',
    'whyChoose.zero': 'Zero',
    'whyChoose.hidden': 'Hidden Costs',
    'whyChoose.promiseDesc': 'We stand behind our work with comprehensive warranties, transparent pricing, and a commitment to delivering exactly what we promise, on time and on budget.',
    'whyChoose.start': 'Start Your Project Today',
    
    // Service Areas
    'serviceAreas.title': 'Service Areas Across Saudi Arabia',
    'serviceAreas.subtitle': 'We provide professional smart home installation services across major cities in Saudi Arabia with local teams and same-day support.',
    'serviceAreas.cities': 'Cities We Serve',
    'serviceAreas.offer': 'What We Offer in Each City',
    'serviceAreas.map': 'Interactive Service Map',
    'serviceAreas.mapDesc': 'View our coverage areas and find the nearest service team to your location.',
    'serviceAreas.viewMap': 'View Full Map',
    'serviceAreas.notListed': 'Don\'t See Your City?',
    'serviceAreas.expanding': 'We\'re expanding our services! Contact us to discuss coverage in your area.',
    'serviceAreas.request': 'Request Service in My Area',
    
    // Contact
    'contact.title': 'Get Your Free Consultation',
    'contact.subtitle': 'Ready to transform your home? Contact us today for a free consultation and personalized smart home solution designed just for you.',
    'contact.schedule': 'Schedule Your Free Consultation',
    'contact.name': 'Full Name',
    'contact.phone': 'Phone Number',
    'contact.email': 'Email Address',
    'contact.service': 'Service Interest',
    'contact.message': 'Message',
    'contact.messagePlaceholder': 'Tell us about your project, home size, specific requirements...',
    'contact.send': 'Send Message',
    'contact.sent': 'Message Sent Successfully!',
    'contact.immediate': 'Need immediate assistance?',
    'contact.immediateDesc': 'Call us now for instant support',
    'contact.whatsapp': 'WhatsApp',
    'contact.emergency': '🚨 Emergency Support',
    'contact.emergencyDesc': 'System down? Security issue? We provide 24/7 emergency support for all our customers with guaranteed response times.',
    'contact.hotline': 'Emergency Hotline: +966 50 XXX XXXX',
    
    // Footer
    'footer.description': 'Saudi Arabia\'s premier smart home automation company. Transforming homes with cutting-edge technology and professional installation services since 2017.',
    'footer.quickLinks': 'Quick Links',
    'footer.services': 'Our Services',
    'footer.serviceAreas': 'Service Areas',
    'footer.followUs': 'Follow Us',
    'footer.copyright': '© 2024 Offer Arabiya. All rights reserved.',
    'footer.privacy': 'Privacy Policy',
    'footer.terms': 'Terms of Service',
    'footer.cookies': 'Cookie Policy',
    
    // Common
    'common.selectService': 'Select a service...',
    'common.required': '*',
    'common.popular': 'Popular',
    'common.projects': 'completed projects',
    'common.from': 'from',
    'common.sar': 'SAR',
  },
  ar: {
    // Header
    'nav.home': 'الرئيسية',
    'nav.services': 'الخدمات',
    'nav.projects': 'المشاريع',
    'nav.about': 'من نحن',
    'nav.contact': 'اتصل بنا',
    'header.phone': '+966 50 XXX XXXX',
    'header.consultation': 'استشارة مجانية',
    
    // Hero
    'hero.title': 'حول منزلك إلى',
    'hero.titleHighlight': 'ملاذ ذكي',
    'hero.subtitle': 'خدمات تركيب أتمتة المنازل المهنية للإضاءة والأمان والصوت وأنظمة التحكم في المناخ في جميع أنحاء المملكة العربية السعودية',
    'hero.getQuote': 'احصل على عرض سعر مجاني',
    'hero.viewWork': 'شاهد أعمالنا',
    'hero.experience': 'سنوات خبرة',
    'hero.homes': 'منزل مؤتمت',
    'hero.certified': 'فنيين معتمدين',
    'hero.warranty': 'ضمان سنتين',
    'hero.warrantyDesc': 'على جميع التركيبات',
    
    // Services
    'services.title': 'خدمات المنزل الذكي',
    'services.subtitle': 'من الأتمتة الأساسية إلى التحول الكامل للمنزل الذكي، نقدم خدمات تركيب شاملة لجميع احتياجات أتمتة منزلك.',
    'services.lighting.title': 'التحكم في الإضاءة الذكية',
    'services.lighting.desc': 'أتمتة الإضاءة الكاملة مع أدوات التحكم في الخفت والإضاءة المزاجية وأنظمة RGB وتكامل LED الموفر للطاقة.',
    'services.lighting.feature1': 'أتمتة التشغيل/الإيقاف',
    'services.lighting.feature2': 'برمجة المشاهد',
    'services.lighting.feature3': 'توفير الطاقة',
    'services.lighting.feature4': 'التحكم الصوتي',
    'services.sensors.title': 'أجهزة الاستشعار والأتمتة',
    'services.sensors.desc': 'أنظمة استشعار متقدمة لكشف الحركة ومراقبة درجة الحرارة والأمان والتحكم البيئي.',
    'services.sensors.feature1': 'كشف الحركة',
    'services.sensors.feature2': 'أجهزة استشعار الحرارة',
    'services.sensors.feature3': 'أجهزة استشعار الأبواب/النوافذ',
    'services.sensors.feature4': 'كشف التسرب',
    'services.audio.title': 'أنظمة الصوت والموسيقى',
    'services.audio.desc': 'توزيع الصوت في المنزل بالكامل مع البث متعدد الغرف والتحكم الصوتي وتركيب المسرح المنزلي.',
    'services.audio.feature1': 'صوت متعدد الغرف',
    'services.audio.feature2': 'التحكم الصوتي',
    'services.audio.feature3': 'المسرح المنزلي',
    'services.audio.feature4': 'الصوت الخارجي',
    'services.curtains.title': 'الستائر والمصاريع',
    'services.curtains.desc': 'معالجات النوافذ الآلية مع التحكم الذكي والجدولة والتكامل مع أنظمة الإضاءة.',
    'services.curtains.feature1': 'ستائر آلية',
    'services.curtains.feature2': 'التحكم بالتطبيق',
    'services.curtains.feature3': 'التشغيل المجدول',
    'services.curtains.feature4': 'أتمتة الخصوصية',
    'services.garage.title': 'التحكم في باب الجراج',
    'services.garage.desc': 'أنظمة أبواب الجراج الذكية مع الوصول عن بُعد وتكامل الأمان وإشعارات الهاتف الذكي.',
    'services.garage.feature1': 'الوصول عن بُعد',
    'services.garage.feature2': 'تكامل الأمان',
    'services.garage.feature3': 'أبواب متعددة',
    'services.garage.feature4': 'إشعارات ذكية',
    'services.climate.title': 'التحكم في المناخ (التكييف)',
    'services.climate.desc': 'تركيب منظم الحرارة الذكي مع التحكم في المناطق وتحسين الطاقة والتكامل مع الأنظمة الأخرى.',
    'services.climate.feature1': 'منظمات حرارة ذكية',
    'services.climate.feature2': 'التحكم في المناطق',
    'services.climate.feature3': 'تحسين الطاقة',
    'services.climate.feature4': 'الإدارة عن بُعد',
    'services.security.title': 'أنظمة السلامة والأمان',
    'services.security.desc': 'أمان شامل مع كاميرات المراقبة والأقفال الذكية وأنظمة الإنذار وقدرات المراقبة على مدار الساعة.',
    'services.security.feature1': 'تركيب كاميرات المراقبة',
    'services.security.feature2': 'أقفال ذكية',
    'services.security.feature3': 'أنظمة الإنذار',
    'services.security.feature4': 'مراقبة 24/7',
    'services.learnMore': 'اعرف المزيد',
    'services.getQuote': 'احصل على عرض سعر مخصص لجميع الخدمات',
    
    // How It Works
    'howItWorks.title': 'كيف نحول منزلك',
    'howItWorks.subtitle': 'عمليتنا المثبتة المكونة من 4 خطوات تضمن تجربة تركيب منزل ذكي سلسة من الاستشارة إلى الدعم المستمر.',
    'howItWorks.step1.title': 'استشارة مجانية',
    'howItWorks.step1.desc': 'يزور الفنيون المعتمدون لدينا منزلك لتقييم احتياجاتك وتقديم حل مخصص يناسب نمط حياتك.',
    'howItWorks.step2.title': 'تصميم مخصص',
    'howItWorks.step2.desc': 'نقوم بإنشاء خطة تركيب مفصلة مع عروض ثلاثية الأبعاد ومواصفات تقنية لنظام أتمتة منزلك.',
    'howItWorks.step3.title': 'تركيب مهني',
    'howItWorks.step3.desc': 'يقوم فريقنا ذو الخبرة بتركيب وتكوين جميع الأنظمة مع الحد الأدنى من الإزعاج لروتينك اليومي.',
    'howItWorks.step4.title': 'التدريب والدعم',
    'howItWorks.step4.desc': 'نقوم بتدريبك على تشغيل النظام ونقدم الدعم المستمر والصيانة والمساعدة التقنية على مدار الساعة.',
    'howItWorks.learnMore': 'اعرف المزيد عن هذه الخطوة ←',
    'howItWorks.startJourney': 'ابدأ رحلة منزلك الذكي اليوم',
    
    // Gallery
    'gallery.title': 'مشاريعنا الحديثة',
    'gallery.subtitle': 'شاهد كيف حولنا المنازل في جميع أنحاء المملكة العربية السعودية بحلول الأتمتة الذكية.',
    'gallery.viewAll': 'عرض جميع المشاريع',
    
    // Benefits
    'benefits.title': 'لماذا تختار أتمتة المنزل الذكي؟',
    'benefits.subtitle': 'حول نمط حياتك مع توفير المال وزيادة قيمة منزلك بحلول الأتمتة المهنية.',
    'benefits.security.title': 'أمان محسن',
    'benefits.security.desc': 'مراقبة وتحكم على مدار الساعة مع الأقفال الذكية والكاميرات وأنظمة الإنذار لراحة البال الكاملة.',
    'benefits.security.stat': '95% تقليل الجريمة',
    'benefits.savings.title': 'توفير الطاقة',
    'benefits.savings.desc': 'قلل فواتير الكهرباء بنسبة تصل إلى 30% مع الإضاءة الذكية والتحكم في المناخ والأنظمة الآلية.',
    'benefits.savings.stat': '30% تقليل الفاتورة',
    'benefits.convenience.title': 'الراحة القصوى',
    'benefits.convenience.desc': 'تحكم في كل شيء من هاتفك الذكي - الأضواء ودرجة الحرارة والأمان وأنظمة الترفيه.',
    'benefits.convenience.stat': 'تحكم بلمسة واحدة',
    'benefits.value.title': 'زيادة قيمة العقار',
    'benefits.value.desc': 'تُباع المنازل الذكية بنسبة 10-15% أكثر من المنازل التقليدية وتجذب المزيد من المشترين.',
    'benefits.value.stat': '15% زيادة في القيمة',
    'benefits.time.title': 'توفير الوقت',
    'benefits.time.desc': 'الروتين والجداول الآلية توفر ساعات كل أسبوع من مهام إدارة المنزل اليدوية.',
    'benefits.time.stat': '5+ ساعات توفر أسبوعياً',
    'benefits.lifestyle.title': 'تحسين نمط الحياة',
    'benefits.lifestyle.desc': 'نوم أفضل وإضاءة مزاجية ودرجة حرارة مثالية وترفيه في متناول يدك.',
    'benefits.lifestyle.stat': '100% رضا',
    'benefits.ready.title': 'مستعد لتجربة هذه الفوائد؟',
    'benefits.ready.desc': 'انضم إلى مئات العملاء الراضين الذين حولوا منازلهم بحلول الأتمتة الذكية من عرض عربية.',
    'benefits.schedule': 'جدولة استشارة مجانية',
    'benefits.calculate': 'احسب مدخراتك',
    
    // Cost Calculator
    'calculator.title': 'حاسبة تكلفة المنزل الذكي',
    'calculator.subtitle': 'احصل على تقدير فوري لمشروع أتمتة منزلك الذكي. خصص بناءً على حجم منزلك والميزات المرغوبة.',
    'calculator.homeSize': 'حجم المنزل (متر مربع)',
    'calculator.rooms': 'عدد الغرف',
    'calculator.services': 'الخدمات المرغوبة (اختر كل ما ينطبق)',
    'calculator.budget': 'نطاق الميزانية (ريال سعودي)',
    'calculator.calculate': 'احسب التقدير',
    'calculator.estimate': 'تقديرك',
    'calculator.total': 'إجمالي الاستثمار',
    'calculator.monthly': 'الدفعة الشهرية (24 شهر)',
    'calculator.savings': 'المدخرات السنوية للطاقة',
    'calculator.included': 'ما هو مشمول:',
    'calculator.installation': 'التركيب والإعداد المهني',
    'calculator.warranty': 'ضمان سنتين على جميع المعدات',
    'calculator.app': 'تكوين تطبيق الهاتف المحمول',
    'calculator.support': 'التدريب والدعم على مدار الساعة',
    'calculator.getQuote': 'احصل على عرض سعر مفصل',
    'calculator.ready': 'مستعد للحساب؟',
    'calculator.readyDesc': 'اختر الخدمات المرغوبة واضغط على احسب لرؤية تقديرك الشخصي.',
    
    // Testimonials
    'testimonials.title': 'ماذا يقول عملاؤنا',
    'testimonials.subtitle': 'انضم إلى مئات العملاء الراضين الذين حولوا منازلهم بحلول الأتمتة المهنية.',
    'testimonials.rating': 'متوسط التقييم',
    'testimonials.customers': 'عملاء سعداء',
    'testimonials.satisfaction': 'معدل الرضا',
    'testimonials.support': 'الدعم متاح',
    'testimonials.join': 'انضم إلى عملائنا السعداء',
    
    // Why Choose Us
    'whyChoose.title': 'لماذا تختار عرض عربية؟',
    'whyChoose.subtitle': 'مع أكثر من 7 سنوات من الخبرة و500+ تركيب ناجح، نحن خبراء أتمتة المنازل الذكية الموثوقون في المملكة العربية السعودية.',
    'whyChoose.experience.title': '7+ سنوات خبرة',
    'whyChoose.experience.desc': 'خبرة واسعة في أتمتة المنازل مع مئات التركيبات الناجحة في جميع أنحاء المملكة العربية السعودية.',
    'whyChoose.customers.title': '500+ عميل راضٍ',
    'whyChoose.customers.desc': 'انضم إلى عائلتنا المتنامية من العملاء السعداء الذين يثقون بنا في احتياجات منازلهم الذكية.',
    'whyChoose.certified.title': 'فنيون معتمدون',
    'whyChoose.certified.desc': 'يتكون فريقنا من محترفين معتمدين مع التدريب المستمر في أحدث تقنيات المنزل الذكي.',
    'whyChoose.warranty.title': 'ضمان سنتين',
    'whyChoose.warranty.desc': 'تغطية ضمان شاملة على جميع التركيبات مع الصيانة والدعم المجاني.',
    'whyChoose.support.title': 'دعم 24/7',
    'whyChoose.support.desc': 'الدعم التقني والصيانة على مدار الساعة للحفاظ على تشغيل منزلك الذكي بشكل مثالي.',
    'whyChoose.consultation.title': 'استشارة مجانية',
    'whyChoose.consultation.desc': 'تقييم منزلي مجاني واستشارة تصميم النظام بدون التزام.',
    'whyChoose.certifications': 'شهاداتنا وشراكاتنا',
    'whyChoose.promise': 'وعدنا لك',
    'whyChoose.quality': 'ضمان الجودة',
    'whyChoose.onTime': 'في الوقت المحدد',
    'whyChoose.delivery': 'تسليم المشروع',
    'whyChoose.zero': 'صفر',
    'whyChoose.hidden': 'تكاليف خفية',
    'whyChoose.promiseDesc': 'نقف وراء عملنا بضمانات شاملة وأسعار شفافة والتزام بتقديم ما نعد به بالضبط، في الوقت المحدد وضمن الميزانية.',
    'whyChoose.start': 'ابدأ مشروعك اليوم',
    
    // Service Areas
    'serviceAreas.title': 'مناطق الخدمة في جميع أنحاء المملكة العربية السعودية',
    'serviceAreas.subtitle': 'نقدم خدمات تركيب المنزل الذكي المهنية في المدن الرئيسية في المملكة العربية السعودية مع فرق محلية ودعم في نفس اليوم.',
    'serviceAreas.cities': 'المدن التي نخدمها',
    'serviceAreas.offer': 'ما نقدمه في كل مدينة',
    'serviceAreas.map': 'خريطة الخدمة التفاعلية',
    'serviceAreas.mapDesc': 'عرض مناطق تغطيتنا والعثور على أقرب فريق خدمة لموقعك.',
    'serviceAreas.viewMap': 'عرض الخريطة الكاملة',
    'serviceAreas.notListed': 'لا ترى مدينتك؟',
    'serviceAreas.expanding': 'نحن نوسع خدماتنا! اتصل بنا لمناقشة التغطية في منطقتك.',
    'serviceAreas.request': 'اطلب الخدمة في منطقتي',
    
    // Contact
    'contact.title': 'احصل على استشارتك المجانية',
    'contact.subtitle': 'مستعد لتحويل منزلك؟ اتصل بنا اليوم للحصول على استشارة مجانية وحل منزل ذكي شخصي مصمم خصيصاً لك.',
    'contact.schedule': 'جدولة استشارتك المجانية',
    'contact.name': 'الاسم الكامل',
    'contact.phone': 'رقم الهاتف',
    'contact.email': 'عنوان البريد الإلكتروني',
    'contact.service': 'اهتمام الخدمة',
    'contact.message': 'الرسالة',
    'contact.messagePlaceholder': 'أخبرنا عن مشروعك وحجم المنزل والمتطلبات المحددة...',
    'contact.send': 'إرسال الرسالة',
    'contact.sent': 'تم إرسال الرسالة بنجاح!',
    'contact.immediate': 'تحتاج مساعدة فورية؟',
    'contact.immediateDesc': 'اتصل بنا الآن للحصول على دعم فوري',
    'contact.whatsapp': 'واتساب',
    'contact.emergency': '🚨 دعم الطوارئ',
    'contact.emergencyDesc': 'النظام معطل؟ مشكلة أمنية؟ نقدم دعم الطوارئ على مدار الساعة لجميع عملائنا مع أوقات استجابة مضمونة.',
    'contact.hotline': 'خط الطوارئ: +966 50 XXX XXXX',
    
    // Footer
    'footer.description': 'شركة أتمتة المنازل الذكية الرائدة في المملكة العربية السعودية. نحول المنازل بالتكنولوجيا المتطورة وخدمات التركيب المهنية منذ 2017.',
    'footer.quickLinks': 'روابط سريعة',
    'footer.services': 'خدماتنا',
    'footer.serviceAreas': 'مناطق الخدمة',
    'footer.followUs': 'تابعنا',
    'footer.copyright': '© 2024 عرض عربية. جميع الحقوق محفوظة.',
    'footer.privacy': 'سياسة الخصوصية',
    'footer.terms': 'شروط الخدمة',
    'footer.cookies': 'سياسة ملفات تعريف الارتباط',
    
    // Common
    'common.selectService': 'اختر خدمة...',
    'common.required': '*',
    'common.popular': 'شائع',
    'common.projects': 'مشاريع مكتملة',
    'common.from': 'من',
    'common.sar': 'ريال سعودي',
  }
};

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<'ar' | 'en'>('en');

  const toggleLanguage = () => {
    setLanguage(prev => prev === 'en' ? 'ar' : 'en');
  };

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, toggleLanguage, t }}>
      <div className={language === 'ar' ? 'rtl' : 'ltr'} dir={language === 'ar' ? 'rtl' : 'ltr'}>
        {children}
      </div>
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};